### ISSUE TITLE
content inspection

### ISSUE THREAD

**Issue by joeldonaldson** [timdenholm/vscode-netscaler#11]
Please add contentinspection as a keyword that is highlighted.  Also, can something be done to make entire interfaces 0/1, 1/1, 10/1, LA/1, LR/1, LO/1, etc show up a single color instead of multiple?

Thanks

**Comment by timdenholm** [comment]
Sure, I'll look at adding these in the next release.

**Comment by joeldonaldson** [comment]
Also IP address should be a single color

**Comment by joeldonaldson** [comment]
The first octet of IP address has the . as a different color
<img width="381" alt="2021-05-27_11-42-52" src="https://user-images.githubusercontent.com/62966950/119865621-7a144580-bee1-11eb-9a5a-78e9592e781c.png">
