### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by sowderca** [timdenholm/vscode-netscaler#17]
**Describe the bug**
Not sure which version the syntax here is based upon but a number of commands are missing, Unless your are only using syntax specific to configuration.

**Expected behavior**
I type `shell` and `shell` is highlighted

**Screenshots**
![image](https://user-images.githubusercontent.com/8977469/198364684-f66d8b06-ea7c-48d3-aa49-8b3da6f36348.png)

**Additional context**
Example of some are the 'Utility' commands found [here](https://developer-docs.citrix.com/projects/citrix-adc-command-reference/en/latest/utility/utility-commands/)

Color theme: [Gruvbox Dark Medium](https://github.com/jdinhify/vscode-theme-gruvbox)

**Comment by timdenholm** [comment]
I'd only ever focused on configuration-specific commands as they're all I've ever needed, but it's quite trivial to add the utility commands you've referenced. I'll add them in and make another release as soon as I have the time.
