### ISSUE TITLE
the word "disable" is appearing coloured when it shouldn't be

### ISSUE THREAD

**Issue by felipe1982** [timdenholm/vscode-netscaler#2]
when the word "disabled" appears anywhere as an argument or option to a command, it appears as coloured (instead of the normal text colour).

It _SHOULD_ appear as a normal text colour.

Try out this command:
`add rewrite policy rw_pol-res-disable-receiver-check "HTTP.REQ.HOSTNAME.SERVER.SET_TEXT_MODE(IGNORECASE).EQ(\"connect-dev.example\")" rw_at-res-disable-receiver-check`

This is how it looks on my vscode:

![Screenshot_49](https://user-images.githubusercontent.com/275621/64755936-355f4400-d570-11e9-859a-a6bd28785604.jpg)

**Comment by timdenholm** [comment]
There's a number of cases where issues like this exist; fortunately it's a simple fix.

I hadn't realised there 600+ installations of the extension since I first published it 😮; I'll fix this one amongst the others and push out another release.

**Comment by timdenholm** [comment]
Yeah I noticed that shortly after I pushed it, I'm still trying to understand TextMate's order of precedence 😕 

It's fixed in the next release now, hopefully I didn't miss anything else 🤞

**Comment by felipe1982** [comment]
It looks even BETTER than it did before! Great work. And I like the link you added to the marketplace page too!
