### ISSUE TITLE
Syntax highlighting doesn't work as shown in demo gif

### ISSUE THREAD

**Issue by pynetscript** [timdenholm/vscode-netscaler#9]
Hi,
- Visual Studio Code 1.41.1
- ns.conf 0.2.2

Highlighting doesn't work like your demo. For example:
- "add", "bind", "SSL", "HTTP", "NEXT", "RESPONSE", "ENABLED" are successfully highlighted blue.
- Anything in quotes ("xxxxxx") is successfully highlighted purple.
- Numbers are successfully highlighted green-ish.
- Comments are successfully highlighted green.

Anything else isn't. For example 
- "server", "service" or "servicegroup" are not highlighted.

**Comment by timdenholm** [comment]
Hi, I'm not yet able to reproduce your issue myself. This what I see running VS Code 1.41.1 and ns.conf 0.2.2:
![working](https://user-images.githubusercontent.com/2860668/71799628-ff5b4800-30a9-11ea-924b-32609308f80a.png)

Are you using the default VS Code theme? Do you mind including a screenshot for me?

Thanks.

**Comment by pynetscript** [comment]
> Are you using the default VS Code theme?  

Yeahhh, was using Dark, switched over to Dark+ and now works as expected. Thank you for your quick response.
